import { IconGallery, IconItem } from '@storybook/blocks';

export const icons20color = {
	name: '20-color',
	icons: ['bankid-multicolor', 'car-damage-multicolor', 'car-multicolor', 'star-filled'],
};

export const icons24 = {
	name: '24',
	icons: [
		'apartment',
		'arrow-growth',
		'arrow-right-enclosed',
		'arrows-apart',
		'attachment',
		'atv',
		'baby',
		'bankid',
		'bell',
		'boat',
		'briefcase',
		'briefcase-first-aid',
		'calendar',
		'calendar-check',
		'calendar-cross',
		'call-center',
		'camera',
		'car',
		'car-damage',
		'caravan',
		'card',
		'card-block',
		'chart-line',
		'chart-pie',
		'chat',
		'check',
		'check-enclosed',
		'chevron-down',
		'chevron-left',
		'chevron-right',
		'chevron-up',
		'circle',
		'clipboard',
		'clock',
		'coins',
		'computer',
		'contract',
		'cross',
		'cross-enclosed',
		'cup',
		'damage',
		'digital-services',
		'document',
		'dog',
		'download',
		'e-invoice',
		'ellipsis-enclosed',
		'envelope',
		'external-link',
		'extra-pinpad',
		'family',
		'farm',
		'flag',
		'gear',
		'gravestones',
		'group',
		'guide',
		'heart',
		'heartbeat',
		'house',
		'house-sun',
		'id-card',
		'id-sign',
		'info-enclosed',
		'institution',
		'lightbulb',
		'list',
		'logout',
		'mc',
		'menu',
		'money',
		'moped',
		'mortgage',
		'padlock',
		'paper',
		'parasol',
		'payment',
		'pdf-document',
		'pension',
		'pension-occupational',
		'pension-private',
		'pension-state',
		'percent',
		'phone',
		'phone-retro',
		'picture',
		'pin',
		'pinpad',
		'plus',
		'pregnant',
		'print',
		'radio-enclosed',
		'radio-round',
		'rv',
		'savings',
		'screen',
		'search',
		'share',
		'shield',
		'smalltruck',
		'snailmail',
		'snowmobile',
		'star',
		'sustainability',
		'swish',
		'tag',
		'text-1-enclosed',
		'text-2-enclosed',
		'text-3-enclosed',
		'tractor',
		'trailer',
		'trash',
		'travel',
		'triangle',
		'umbrella',
		'user',
		'user-glow',
		'user-happy',
		'wallet',
		'wallet-minus',
		'wallet-plus',
		'warning',
		'write',
	],
};
export const icons24color = {
	name: '24-color',
	icons: ['bankid-multicolor', 'car-damage-multicolor', 'car-multicolor', 'card-multicolor'],
};

export const icons20 = {
	name: '20',
	icons: [
		'arrow-growth',
		'arrow-right-enclosed',
		'arrows-apart',
		'attachment',
		'bankid',
		'boat',
		'breifcase-first-aid',
		'briefcase',
		'calendar',
		'calendar-check',
		'calendar-cross',
		'car',
		'card',
		'card-block',
		'chat',
		'check',
		'check-enclosed',
		'chevron-down',
		'chevron-left',
		'chevron-right',
		'chevron-up',
		'clipboard',
		'clock',
		'coins',
		'contentcard',
		'cross',
		'cross-enclosed',
		'document',
		'dog',
		'ellipsis-enclosed',
		'envelope',
		'external-link',
		'external-link-inline',
		'family',
		'first-aid',
		'flag',
		'gear',
		'globe',
		'gravestones',
		'heart',
		'heartbeat',
		'house',
		'house-sun',
		'id-card',
		'info-enclosed',
		'institution',
		'letter',
		'login-device',
		'logout',
		'menu',
		'minpension',
		'money',
		'paper',
		'pdf-document',
		'pension',
		'pension-capital',
		'pension-occupational',
		'pension-private',
		'pension-state',
		'percent',
		'phone-broken',
		'phone-retro',
		'pin',
		'plus',
		'print',
		'radio-enclosed',
		'radio-round',
		'screen',
		'search',
		'share',
		'shield',
		'star',
		'suitcase',
		'sustainability',
		'swish',
		'tag',
		'text-1-enclosed',
		'text-2-enclosed',
		'text-3-enclosed',
		'thumbs-up',
		'trash',
		'triangle',
		'umbrella',
		'user',
		'wallet',
		'wallet-minus',
		'wallet-plus',
		'world',
	],
};

export const icons32 = {
	name: '32',
	icons: [
		'accounts',
		'apartment',
		'arrow-growth',
		'arrow-right-enclosed',
		'arrows-apart',
		'attach',
		'atv',
		'baby',
		'bell',
		'boat',
		'briefcase',
		'briefcase-first-aid',
		'calendar',
		'calendar-check',
		'calendar-cross',
		'call-center',
		'car',
		'car-damage',
		'caravan',
		'card',
		'card-block',
		'chart-pie',
		'chat',
		'check',
		'check-bold',
		'check-enclosed',
		'chevron-down',
		'chevron-left',
		'chevron-right',
		'chevron-up',
		'circle',
		'clipboard',
		'clock',
		'coins',
		'computer',
		'contract',
		'cross',
		'cross-enclosed',
		'cup',
		'damage',
		'digital-services',
		'document',
		'dog',
		'e-invoice',
		'ellipsis-enclosed',
		'external-link',
		'facebook',
		'family',
		'farm',
		'filetransfer',
		'flag',
		'gear',
		'globe',
		'gravestone',
		'group',
		'guide',
		'heart',
		'heartbeat',
		'house',
		'house-sun',
		'id-card',
		'info-enclosed',
		'instagram',
		'institution',
		'letter',
		'linkedin',
		'list',
		'login-bankid',
		'login-device',
		'login-pincode',
		'logout',
		'mc',
		'menu',
		'menu-envelope',
		'money',
		'moped',
		'mortgage',
		'padlock',
		'paper',
		'parasol',
		'payment',
		'pdf-document',
		'pension',
		'pension-capital',
		'pension-occupational',
		'pension-private',
		'pension-state',
		'percent',
		'phone',
		'phone-landscape',
		'phone-retro',
		'pin',
		'plus',
		'pregnant',
		'print',
		'radio-enclosed',
		'radio-round',
		'rv',
		'savings',
		'savings-alt',
		'screen',
		'search',
		'shield',
		'smalltruck',
		'snailmail',
		'snowmobile',
		'star',
		'sustainability',
		'swish',
		'tag',
		'text-1-enclosed',
		'text-2-enclosed',
		'text-3-enclosed',
		'thumbs-down',
		'thumbs-up',
		'tractor',
		'trailer',
		'trash',
		'travel',
		'triangle',
		'twitter',
		'umbrella',
		'user-glow',
		'user-happy',
		'wallet',
		'wallet-minus',
		'wallet-open',
		'wallet-plus',
		'world',
		'write',
		'youtube',
	],
};

export const icons32color = {
	name: '32-color',
	icons: [
		'bankid-multicolor',
		'broken-window-multicolor',
		'car-damage-multicolor',
		'car-multicolor',
		'card-multicolor',
		'house-multicolor',
		'money-multicolor',
		'moose-multicolor',
		'offer-multicolor',
		'savings-multicolor',
		'travel-multicolor',
	],
};

export const icons40 = {
	name: '40',
	icons: [
		'apartment',
		'arrow-growth',
		'arrows-apart',
		'atv',
		'baby',
		'bankid',
		'bike',
		'bird',
		'boat',
		'briefcase',
		'briefcase-first-aid',
		'camera',
		'car',
		'car-damage',
		'caravan',
		'card',
		'card-block',
		'chart-line',
		'chart-pie',
		'chat',
		'check',
		'circle',
		'clipboard',
		'clock',
		'coins',
		'computer',
		'contract',
		'cross',
		'cup',
		'damage',
		'digital-services',
		'document',
		'dog',
		'dog-alt',
		'e-invoice',
		'envelope',
		'facebook',
		'family',
		'farm',
		'fish',
		'gear',
		'glasses',
		'gravestones',
		'group',
		'guide',
		'heart',
		'heartbeat',
		'house',
		'house-sun',
		'id-sign',
		'institution',
		'letter',
		'mc',
		'money',
		'moped',
		'mortgage',
		'padlock',
		'parasol',
		'payment',
		'pension-occupational',
		'pension-private',
		'pension-state',
		'percent',
		'phone',
		'phone-broken',
		'phone-landscape',
		'phone-retro',
		'pin',
		'pregnant',
		'radio-enclosed',
		'rv',
		'savings',
		'shield',
		'smalltruck',
		'snailmail',
		'snowmobile',
		'star',
		'sustainability',
		'swish',
		'tablet',
		'tag',
		'thumb-up',
		'tractor',
		'trailer',
		'travel',
		'twitter',
		'umbrella',
		'user-glow',
		'user-happy',
		'wallet',
		'world',
		'wristwatch',
	],
};

export const icons40color = {
	name: '40-color',
	icons: ['bankid-multicolor', 'damage-multicolor'],
};

const variants = [
	icons20color,
	icons24,
	icons24color,
	icons20,
	icons32,
	icons32color,
	icons40,
	icons40color,
];

function createIconList() {
	const list = {};

	variants.forEach((variant) => {
		variant.icons.forEach((icon) => {
			if (list[icon]) {
				if (list[icon].indexOf(variant.name)) {
					list[icon].push(variant.name);
				}
			} else {
				const values = new Array();
				values.push(variant.name);
				list[icon] = values;
			}
		});
	});

	return list;
}

const iconList = createIconList();

export function Icons({ name, size }) {
	const iconSize = size.split('-color')[0];
	return (
		<div class="icon-preview" title={iconSize}>
			<svg class="icon" width={iconSize} height={iconSize}>
				<use href={`lf-icons/sprite/${size}/icons.svg#${name}-${iconSize}`}></use>
			</svg>
		</div>
	);
}

function renderIconItem([name, sizes]) {
	const sorted = [...sizes].sort((a, b) => {
		if (a > b) {
			return -1;
		}
		if (b > a) {
			return 1;
		}
		return 0;
	});

	return (
		<div class="icon-item">
			<div class="icon-item__name">{name}</div>
			<div class="icon-item__sizes">
				{sorted.map((size) => (
					<Icons name={name} size={size} />
				))}
			</div>
		</div>
	);
}

export function IconGroup() {
	return (
		<div class="icon-gallery">{Object.entries(iconList).map((icon) => renderIconItem(icon))}</div>
	);
}
