name: CI
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Create .npmrc
        uses: bikutadesu/create-npmrc@v1.0.0
        with:
          org_name: lf-digitala-kanaler
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          always_auth: true

      - name: Install
        run: npm install

      - name: Test
        run: npm test
